ports:
  inputs:
  - identifier: in_adamant_antigen
    name: LoopBe Internal MIDI 0
    port: null
    port_type: USB
  outputs:
  - identifier: out_boiling_button
    name: Microsoft GS Wavetable Synth 0
    port: null
    port_type: USB
  - identifier: out_craven_cherry
    name: LoopBe Internal MIDI 1
    port: null
    port_type: USB
mappings:
- from_port: ALL
  to_port: ALL
  from_channel: ALL
  to_channel: ALL
