[project]
name = "MidiRouter"
version = "0.1.0alpha1"
dependencies = [
  "mido[ports-rtmidi]",
  "pydantic",
  "pyyaml",
  "wonderwords",
  "chordelia",
  "textual>=6.4.0",
  "rich",
]

[project.scripts]
midi-router-cli = "midi_router.scripts.cli:main"
midi-router-interactive = "midi_router.scripts.interactive:main"


[tool.setuptools]
package-dir = {"" = "src"}
packages = ["midi_router"]

[tool.uv]
package = true

[dependency-groups]
dev = [
    "ipython>=9.6.0",
  "textual-dev>=1.8.0",
  "pytest>=7.0",
  "pytest-asyncio>=0.20",
]
